services:
  - type: web
    name: pranjal-engitech-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: DB_NAME
        value: pranjal_engitech
      - key: REQUIRE_MONGO
        value: true
      - key: REQUIRE_CLOUDINARY
        value: true
      - key: SECRET_KEY
        sync: false
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: API_ADMIN_TOKEN
        sync: false
      - key: MONGO_URI
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
